name: "Commit"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run jemalloc action
        uses: ./

      - name: "Install JDK"
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '22'

      - name: Start Background Process with Infinite Loop
        run: |
          nohup bash -c 'echo "public class Main { public static void main(String[] args) { while (true) { try { Thread.sleep(10000); } catch (InterruptedException e) {} } } }" > Main.java && javac Main.java && java Main' &
          echo $! > background_process.pid

      - name: Check jemalloc Usage
        run: |
          # Load the PID of the background process
          export PID=$(cat background_process.pid)
          ./scripts/mac/verify.sh "$PID"

      - name: Cleanup Background Process
        run: |
          # Kill the background process if it is still running
          if [ -f background_process.pid ]; then
            kill $(cat background_process.pid) || true
            rm background_process.pid
          fi
  # windows:
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Run jemalloc action
  #       uses: ./
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run jemalloc action
        uses: ./

      - name: Start Background Process with Infinite Loop
        run: |
          nohup bash -c 'while true; do sleep 10; done' &
          echo $! > background_process.pid

      - name: Check jemalloc Usage
        run: |
          # Load the PID of the background process
          export PID=$(cat background_process.pid)
          ./scripts/linux/verify.sh "$PID"

      - name: Cleanup Background Process
        run: |
          # Kill the background process if it is still running
          if [ -f background_process.pid ]; then
            kill $(cat background_process.pid) || true
            rm background_process.pid
          fi